#!/usr/bin/env python3
"""Build Chinese and English ChatGPT entries from their workflow sources."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "skills/editorial-avatar/references/workflow.md"
TARGET = ROOT / "prompts/chatgpt.md"
SOURCE_EN = ROOT / "skills/editorial-avatar/references/workflow.en.md"
TARGET_EN = ROOT / "prompts/chatgpt.en.md"
HEADER = """<!-- Generated by scripts/build_prompt.py; edit references/workflow.md instead. -->
# ChatGPT 入口

第一条消息复制下方“方案阶段”，附上人物照片并说明用途。可选附上本项目的 style-anchor.png，并明确哪张是人物、哪张仅作风格参考。不要仅发送本地路径，ChatGPT 无法读取你电脑上的文件。方案完成后发送第二条“生成阶段”。

## 方案阶段

```text
本轮只做肖像设计沟通，不调用图像生成或编辑工具。下面流程中的“生成与修改”和“审片与交付”在我下一条明确发送“按方案生成”后才执行。
先确认实际用途；用途缺失时只问用途并结束本轮。用途明确且照片可见时，由你给出一份简短完整的创作方案，不要求我选择摄影参数。缺少人物照片时请我附上，不猜测人物长相。

"""
FOOTER = """\n\n现在执行方案阶段；本轮不生成图片。\n```

## 生成阶段

确认方案后，在同一对话中发送：

```text
按方案生成。用我提供的人物照片作为身份参考，有风格参考时只借鉴绘画语言。请直接交付图片，并按实际用途检查成片；只有确实检查过的项目才能说已通过。
```

后续修改直接说具体变化，例如：“保留这一版构图和服装，只去掉眼镜。”
"""
HEADER_EN = """<!-- Generated by scripts/build_prompt.py from references/workflow.en.md; keep the translation aligned with workflow.md. -->
# ChatGPT entry (English)

Copy the "Planning stage" block into a ChatGPT conversation with image generation, attach the person's photo, and state where the portrait will be used. You may also attach this project's style-anchor.png; identify which image is the person and which is only a style reference. Attach the actual images, not local file paths. After reviewing the plan, send the "Generation stage" message in the same conversation. [中文版](chatgpt.md). One logged-in Chrome trial of this English two-stage flow is recorded in the [validation log](../VALIDATION.en.md).

## Planning stage

```text
This turn is only for discussing and planning the portrait. Do not call image generation or editing tools. Defer the "Generate and revise" and "Review and deliver" sections below until my next explicit message, "Generate according to the plan."
First establish the actual use. If it is missing, ask only where the image will be used and end this turn. If the use is clear and the photo is visible, provide a short, complete creative plan without asking me to choose photography parameters. If the person's photo is missing, ask me to attach it; do not guess their appearance.

"""
FOOTER_EN = """\n\nCarry out the planning stage now; do not generate an image in this turn.\n```

## Generation stage

After reviewing the plan, send this in the same conversation:

```text
Generate according to the plan. Use the person's photo I attached as the identity reference. If I also provided a style reference, borrow only its visual language. Deliver the image directly and review it for its actual use; claim a check passed only if you performed it.
```

For later edits, state the specific change, for example: "Keep this composition and outfit; only remove the glasses."
"""


def render(source, header, footer):
    return header + source.read_text(encoding="utf-8").strip() + footer


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated prompt is stale")
    args = parser.parse_args()
    for source, target, header, footer in (
        (SOURCE, TARGET, HEADER, FOOTER),
        (SOURCE_EN, TARGET_EN, HEADER_EN, FOOTER_EN),
    ):
        result = render(source, header, footer)
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != result:
                parser.exit(1, f"{target.relative_to(ROOT)} is stale; run python3 scripts/build_prompt.py\n")
            print(f"{target.relative_to(ROOT)} is synchronized")
        else:
            target.write_text(result, encoding="utf-8")
            print(target.relative_to(ROOT))
