#!/usr/bin/env python3
"""Build the copyable ChatGPT entry from the shared workflow, without dependencies."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "skills/editorial-avatar/references/workflow.md"
TARGET = ROOT / "prompts/chatgpt.md"
HEADER = """<!-- Generated by scripts/build_prompt.py; edit references/workflow.md instead. -->
# ChatGPT 入口

第一条消息复制下方“方案阶段”，附上人物照片并说明用途。可选附上本项目的 style-anchor.png，并明确哪张是人物、哪张仅作风格参考。不要仅发送本地路径，ChatGPT 无法读取你电脑上的文件。方案完成后发送第二条“生成阶段”。

## 方案阶段

```text
本轮只做肖像设计沟通，不调用图像生成或编辑工具。下面流程中的“生成与修改”和“审片与交付”在我下一条明确发送“按方案生成”后才执行。
先确认实际用途；用途缺失时只问用途并结束本轮。用途明确且照片可见时，由你给出一份简短完整的创作方案，不要求我选择摄影参数。缺少人物照片时请我附上，不猜测人物长相。

"""
FOOTER = """\n\n现在执行方案阶段；本轮不生成图片。\n```

## 生成阶段

确认方案后，在同一对话中发送：

```text
按方案生成。用我提供的人物照片作为身份参考，有风格参考时只借鉴绘画语言。请直接交付图片，并按实际用途检查成片；只有确实检查过的项目才能说已通过。
```

后续修改直接说具体变化，例如：“保留这一版构图和服装，只去掉眼镜。”
"""


def render():
    return HEADER + SOURCE.read_text(encoding="utf-8").strip() + FOOTER


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated prompt is stale")
    args = parser.parse_args()
    result = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != result:
            parser.exit(1, "ChatGPT prompt is stale; run python3 scripts/build_prompt.py\n")
        print("ChatGPT prompt is synchronized")
    else:
        TARGET.write_text(result, encoding="utf-8")
        print(TARGET.relative_to(ROOT))
